# torchtitan Config.toml
# NOTE: this toml config is a preset for 64 A100 GPUs.

[job]
dump_folder = "./outputs"
description = "Llama 3 8B training"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 1
enable_tensorboard = true
save_tb_folder = "tb"
enable_wandb = true

[model]
name = "meta-llama/Llama-3.1-8B"
num_quantizers = 4
# converters = ["float8"]

[optimizer]
name = "AdamW"
lr = 3e-4
eps = 1e-8

[lr_scheduler]
warmup_steps = 1500  # lr scheduler warm up
decay_ratio = 0.2
lr_min = 0.1

[training]
local_batch_size = 8
global_batch_size = 1024
seq_len = 1024
max_norm = 1.0  # grad norm clipping
steps = 100_000
compile = false
dataset = "all" #"libri_light"
task = "a2a"

[validation]
enabled = true
dataset = "librispeech_asr"
local_batch_size = 8
seq_len = 1024
freq = 100
steps = 10

[evaluation]
enable_evaluation = false
evaluation_freq = 500

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
pipeline_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval = 1000
last_save_model_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]
keep_latest_k = 10

[activation_checkpoint]
mode = "none"  # ["none", "selective", "full"]
selective_ac_option = "op"  # "int" = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
filter_fqns = ["output"]
